apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitops-demo-base

resources:
- deployment.yaml
- service.yaml
- quarkus-deployment.yaml
- quarkus-service.yaml

commonLabels:
  managed-by: argocd
  version: v1.0.0

images:
- name: gitops-demo
  newName: ghcr.io/vermasuraj10678/gitops/gitops-demo
  newTag: latest