apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-dev

namePrefix: dev-

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: dev

images:
- name: gitops-demo
  newTag: dev-latest