apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-staging

namePrefix: staging-

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: staging

images:
- name: gitops-demo
  newTag: staging-latest