apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-staging

namePrefix: staging-

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: staging

images:
- name: gitops-demo
  newName: ghcr.io/vermasuraj10678/gitops/gitops-demo
  newTag: main-02b3ee3
